server:
  port: 9200
  max-http-header-size: 756000
  jetty:
    threads:
      min: 100
      max: 3000
      idle-timeout: 10000
    connection-idle-timeout: 10000
    accesslog:
      enabled: true

spring:
  application:
    name: spring_boot_web_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: saber66
    password: AdminSaber66
    hikari:
      max-lifetime: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 10000
      idle-timeout: 10000
      keepalive-time: 10000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true


service:
  api:
    base-path: /services/${spring.application.name}
  swagger:
    title: 'spring boot web demo'
    description: 'this is sample spring boot application web demo'
    version : 'version1.0.0-1401/08/16'

springdoc:

  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
    operations-sorter: alpha


  api-docs:
    path: /services/${spring.application.name}/v3/api-docs

camel:
  springboot:
    producer-template-cache-size: 3000
    dump-routes: true

  dataformat:
    jackson:
      auto-discover-object-mapper: true
      pretty-print: true


management:
  endpoints:
    web:
      base-path: /actuators/${spring.application.name}
      exposure:
        include: '*'
