server:
  port: 9200
  tomcat:
    threads:
      max: 500
      min-spare: 50
    connection-timeout: 10000
    accesslog:
      enabled: true
      encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  application:
    name: spring_boot_web_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: saber66
    password: AdminSaber66
    hikari:
      max-lifetime: 10000
      maximum-pool-size: 6
      minimum-idle: 3
      connection-timeout: 10000
      idle-timeout: 10000
      keepalive-time: 10000
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true


service:
  api:
    base-path: /services/${spring.application.name}
  swagger:
    title: 'spring boot web demo'
    description: 'this is sample spring boot application web demo'
    version : 'version1.1.0-1404/02/23'

springdoc:

  swagger-ui:
    path: /swagger
    display-request-duration: true
    display-operation-id: true
    operations-sorter: alpha


  api-docs:
    path: ${service.api.base-path}/v3/api-docs

camel:
  dataformat:
    jackson:
      auto-discover-object-mapper: true
      pretty-print: true

management:
  endpoints:
    web:
      base-path: /actuators/${spring.application.name}
      exposure:
        include: '*'
